AWS 0:
  serviceName: amazon-web-services
  configName: AWSAssetSync0
  configurationAttributes:
    valueClass: Object
    objectType: service_configuration
    properties:
      region:
        valueClass: Array
        items:
        - valueClass: String
          value: All regions
      consoleInsideAWS:
        valueClass: Boolean
        value: true
      engineInsideAWS:
        valueClass: Boolean
        value: false
      arn:
        valueClass: Array
        items:
        - valueClass: String
          value: 'arn:aws:iam::000000000000:role/ExampleTestRole0'
      useProxy:
        valueClass: Boolean
        value: false
AWS 1:
  serviceName: amazon-web-services
  configName: AWSAssetSync1
  configurationAttributes:
    valueClass: Object
    objectType: service_configuration
    properties:
      region:
        valueClass: Array
        items:
        - valueClass: String
          value: US East (N. Virginia)
      consoleInsideAWS:
        valueClass: Boolean
        value: true
      engineInsideAWS:
        valueClass: Boolean
        value: false
      arn:
        valueClass: Array
        items:
        - valueClass: String
          value: 'arn:aws:iam::000000000000:role/ExampleTestRole1'
      useProxy:
        valueClass: Boolean
        value: false
AWS 2:
  serviceName: amazon-web-services
  configName: AWSAssetSync2
  configurationAttributes:
    valueClass: Object
    objectType: service_configuration
    properties:
      region:
        valueClass: Array
        items:
        - valueClass: String
          value: All regions
      consoleInsideAWS:
        valueClass: Boolean
        value: true
      engineInsideAWS:
        valueClass: Boolean
        value: false
      arn:
        valueClass: Array
        items:
        - valueClass: String
          value: 'arn:aws:iam::000000000000:role/ExampleTestRole2'
      useProxy:
        valueClass: Boolean
        value: false